package br.com.terras.app.dsm.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFF7F9FF)
val md_theme_light_secondary = Color(0xFF4B5166)
val md_theme_light_tertiary = Color(0xFF979797)
val md_theme_light_error = Color(0xFFFF2C7B)
val md_theme_light_background = Color(0xFFF4F6FC)
val md_theme_light_surface = Color(0xFF292E3F)
val md_theme_light_outline = Color(0xFF817567)
val md_theme_light_inverseSurface = Color(0xFF34302A)
val md_theme_light_inversePrimary = Color(0xFFFFB951)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFFFB951)
val md_theme_light_outlineVariant = Color(0xFFD3C4B4)
val md_theme_light_scrim = Color(0xFF2CFF8C)
val md_theme_dark_primary = Color(0xFF323748)
val md_theme_dark_secondary = Color(0xFF4B5166)
val md_theme_dark_tertiary = Color(0xFF4B5166)
val md_theme_dark_error = Color(0xFFFF2C7B)
val md_theme_dark_background = Color(0xFF292E3F)
val md_theme_dark_surface = Color(0xFFFFFFFF)
val md_theme_dark_outline = Color(0xFF9C8F80)
val md_theme_dark_inverseSurface = Color(0xFFEAE1D9)
val md_theme_dark_inversePrimary = Color(0xFF825500)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB951)
val md_theme_dark_outlineVariant = Color(0xFF4F4539)
val md_theme_dark_scrim = Color(0xFF2CFF8C)