name: Android CI

on:
  push:
    branches:
      -  master

  pull_request:
    branches: 
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: set up JDK 11
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '18'
        distribution: 'corretto'

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew test -x koverXmlReportDebug

    - name: Run Converage
      run: ./gradlew koverXmlReportDebug
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        slug: gustavoterras/CryptoTrend
        fail_ci_if_error: false # optional (default = false)
        files: app/build/reports/kover/reportDebug.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        token: ${{ secrets.CODECOV_TOKEN }} # required
        verbose: true # optional (default = false)

    # - name: SonarCloud Scan
    #   uses: sonarsource/sonarcloud-github-action@v2.3.0
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Upload test report
      uses: actions/upload-artifact@v4.3.3
      with:
          name: reportDebug.xml
          path: app/build/reports/kover/reportDebug.xml

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: CryptoTrend.apk
        path: app/build/outputs/apk/debug/app-debug.apk
